const seedDate = [
  {
    firstName: 'Kafka',
    lastName: 'Lane',
    enrollMonth: 'October',
    enrollYear: '2016',
  },
  {
    firstName: 'John',
    lastName: 'Smith',
    enrollMonth: 'January',
    enrollYear: '2016',
  },
  {
    firstName: 'Drew',
    lastName: 'Koli',
    enrollMonth: 'February',
    enrollYear: '2016',
  },
  {
    firstName: 'Evan',
    lastName: 'Brown',
    enrollMonth: 'February',
    enrollYear: '2016',
  },
  {
    firstName: 'Mike',
    lastName: 'Jones',
    enrollMonth: 'March',
    enrollYear: '2016',
  },
  {
    firstName: 'Alvin',
    lastName: 'Musk',
    enrollMonth: 'April',
    enrollYear: '2016',
  },
  {
    firstName: 'George',
    lastName: 'Wash',
    enrollMonth: 'May',
    enrollYear: '2016',
  },
  {
    firstName: 'Steven',
    lastName: 'Jonson',
    enrollMonth: 'May',
    enrollYear: '2016',
  },
  {
    firstName: 'Steph',
    lastName: 'Alan',
    enrollMonth: 'May',
    enrollYear: '2016',
  },
  {
    firstName: 'Juliet',
    lastName: 'Jay',
    enrollMonth: 'June',
    enrollYear: '2016',
  },
  {
    firstName: 'Heidi',
    lastName: 'Mane',
    enrollMonth: 'July',
    enrollYear: '2016',
  },
  {
    firstName: 'Alphonso',
    lastName: 'Rogers',
    enrollMonth: 'August',
    enrollYear: '2016',
  },
  {
    firstName: 'Mark',
    lastName: 'Allison',
    enrollMonth: 'September',
    enrollYear: '2016',
  },
  {
    firstName: 'Aaron',
    lastName: 'Alano',
    enrollMonth: 'October',
    enrollYear: '2016',
  },
  {
    firstName: 'Derek',
    lastName: 'Smithy',
    enrollMonth: 'November',
    enrollYear: '2016',
  },
  {
    firstName: 'Emma',
    lastName: 'Lull',
    enrollMonth: 'December',
    enrollYear: '2016',
  },
  {
    firstName: 'Baxter',
    lastName: 'Nos',
    enrollMonth: 'October',
    enrollYear: '2016',
  },
  {
    firstName: 'Yvette',
    lastName: 'Slaw',
    enrollMonth: 'October',
    enrollYear: '2016',
  },
  {
    firstName: 'Eliz',
    lastName: 'Jonas',
    enrollMonth: 'October',
    enrollYear: '2016',
  },
  {
    firstName: 'Rodeny',
    lastName: 'Rogers',
    enrollMonth: 'October',
    enrollYear: '2016',
  },
  {
    firstName: 'Phil',
    lastName: 'Lane',
    enrollMonth: 'October',
    enrollYear: '2016',
  },
  {
    firstName: 'Trevor',
    lastName: 'Trod',
    enrollMonth: 'April',
    enrollYear: '2016',
  },
]
